### ISSUE TITLE
field component is not taking width and placeholder property

### ISSUE THREAD

**Issue by mamezito-zz** [k-vyn/framer-ios-kit#11]
http://share.framerjs.com/8yl3lio7l4hs/

setting up width and placeholder text according to docs doesnt do anything

**Comment by k-vyn** [comment]
Ah super sorry, I rewrote the field component without updating the documentation. I'm working on updating it now.

The short answer is the prop changed from placeholderText to just placeholder. http://share.framerjs.com/wn5a3qs0bs9y/

FYI, these are the current props you can set on the field - name, active(true/false), keyboard (pass a keyboard object to it), placeholder, placeholderColor, superLayer, backgroundColor, borderColor, borderRadius, borderWidth, height, width, fontSize, color, textConstraints, constraints.

**Comment by mamezito-zz** [comment]
no worries, its not critical), will check new properties
