### ISSUE TITLE
Change color in Navbar component

### ISSUE THREAD

**Issue by theposch** [k-vyn/framer-ios-kit#13]
When changing the text color of a label in the NavBar component, it changes back to blue after click. Can this be edited?

`nav.left.label.color = 'white'
`

**Comment by theposch** [comment]
Figured it out.

**Comment by k-vyn** [comment]
Thanks for sending this! Just pushed the fix. I'm working on updating the doc, but I added these properties to the navbar, so you don't have to set this after declaration – 

<pre>
color
titleColor
backgroundColor
dividerBackgroundColor:
</pre>
