### ISSUE TITLE
Field - Placeholder text doesn't seem to work

### ISSUE THREAD

**Issue by theposch** [k-vyn/framer-ios-kit#15]
Seems like entering placeholder text for a field doesn't seem to work.

<img width="1482" alt="screen shot 2016-08-22 at 12 58 22 pm" src="https://cloud.githubusercontent.com/assets/5529148/17852559/3f578df0-6868-11e6-9798-a53ee29ceb9e.png">

**Comment by mamezito-zz** [comment]
it works, just docs are outdated, use placeholder:"search" instead of placeholderText

**Comment by theposch** [comment]
Amazing! Thanks @mamezito
