### ISSUE TITLE
Refactor into more than one file

### ISSUE THREAD

**Issue by joshpuckett** [k-vyn/framer-ios-kit#2]
First of all, this module is A++ legit :) Well done.

One tiny bit of feedback or advice would be to break them apart into semantic files and then use 'require' to bring it all into one. This will make it much easier both to scale and for others to help work on it.

Keep it up!

**Comment by k-vyn** [comment]
Thank you so much! That means a lot. 

Yeah, I completely agree. It's a little cumbersome right now. I'm currently working on a big refactor, and I'm breaking it up into smaller files, and then having that one coffee file that'll build it. It should be a lot easier to work on then.

**Comment by jordandobson** [comment]
👌🏻
