### ISSUE TITLE
when using a parent, constraints don't seem to be honoured

### ISSUE THREAD

**Issue by lewf** [k-vyn/framer-ios-kit#8]
Really great module!  I would suggest taking a look at the constraint system as it relates to child layers - unless I'm misunderstanding something, the constraints seem to break when parenting an object to another...

Simple example:
<img width="1374" alt="screen shot 2016-06-25 at 07 52 19" src="https://cloud.githubusercontent.com/assets/18259073/16354977/2f4e9a62-3aa9-11e6-8a53-d015bdef96de.png">

**Comment by k-vyn** [comment]
The last update I believe should resolve this bug. It's working for me. Can you let me know if it doesn't for you?

**Comment by lewf** [comment]
Works perfectly 👍
